[ids]
*

[main]
# Maps Caps Lock to Escape when tapped, and Control when held
# (Pro tip: Having Control on Caps is a game changer for shortcuts)
capslock = overload(control, esc)

[alt]
# Your requested Return binding
capslock = enter
; = enter

# browser type shi
t = C-t
q = C-tab

# Your WASD Navigation
w = up
a = left
s = down
d = right

#Vim Navigation
h = left
j = down
k = up
l = right

# --- The "Hella Helpful" Additions ---

e = backspace

# Media Controls (Because reaching for F-keys is a chore)
1 = previoussong
2 = playpause
3 = nextsong
4 = volumedown
5 = volumeup

[meta]
capslock = S-;

[alt+shift]
w = C-w
l = C-l
